version: '3.5'

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host:traefik.${DOMAIN}'
      traefik.frontend.auth.basic: '${TRAEFIK_DASHBOARD_CREDENTIALS}'
      traefik.port: '8080'
    ports:
      - 80:80    
      - 443:443  
    expose:
      - 8080
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PWD}/conf/traefik.toml:/traefik.toml
        - ${PWD}/certs/:/certs/
    healthcheck:
      test: ["CMD", "/traefik", "healthcheck"]
      start_period: 2s
    restart: on-failure:20
    logging:
      driver: json-file
      options:
        max-size: '10m'

networks:
  default:
    external:
      name: traefik
