version: '3.5'

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entrypoints:  websecure
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.middlewares: admin
      traefik.http.middlewares.admin.basicauth.users: '${TRAEFIK_DASHBOARD_CREDENTIALS}'

      # global redirect to https
      traefik.http.routers.http-catchall.rule : hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-to-https

      # middleware redirect
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https

    ports:
      - 80:80
      - 443:443
    
    expose:
      - 8080
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PWD}/conf/traefik.yaml:/traefik.yaml
        - ${PWD}/conf/dynamic.yaml:/dynamic.yaml
        - ${PWD}/certs/:/certs/

    restart: on-failure:20
    logging:
      driver: json-file
      options:
        max-size: '10m'

networks:
  default:
    external:
      name: traefik
