debug = false

logLevel = "DEBUG"


defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
[entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [entryPoints.https.tls.defaultCertificate]
      certFile = "/cert/whoami.cert"
      keyFile = "/cert/whoami.key"
 
[api]
entrypoint="traefik"


[ping]
  entryPoint = "traefik"


[metrics]
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]
    
  # Optional Default: "traefik"
  # entryPoint = "traefik"
    
  # Optional  Default: [0.1, 0.3, 1.2, 5.0]
  # buckets = [0.1,0.3,1.2,5.0]


[tracing]
  [tracing.jaeger]
    localAgentHostPort = "jaeger:6831"
    SamplingServerURL = "http://jaeger:5778/sampling"
    serviceName = "traefik-back"
    backend = "jaeger"


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "whoami.local"
watch = true
exposedByDefault = false
