#static conf

log: 
  level: DEBUG

metrics:
  prometheus : {}

tracing:
  jaeger:
    samplingServerURL: http://jaeger:5778/sampling
    localAgentHostPort : jaeger:6831
    traceContextHeaderName : ndia-trace-id

providers:
  docker:
    endpoint : "unix:///var/run/docker.sock"
    watch : true
    exposedByDefault : false
    network : "traefik"
  file:
    filename: "dynamic.yaml"
    watch : true

api:
  dashboard: true
  debug : true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
